# Generated by Django 5.2.5 on 2025-09-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentHistory',
            fields=[
                ('receipt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('school_year', models.CharField(max_length=9)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreasurerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('must_change_password', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.studentrecord')),
                ('password', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
