# Generated by Django 5.2.5 on 2025-09-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasureraccount',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='treasureraccount',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
