# Generated by Django 5.2.5 on 2025-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpaymenthistory',
            name='added_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
